[build]
publish = "public"
command = "npm run build:hugo"

[build.environment]
GO_VERSION = "1.19"
HUGO_VERSION = "0.112.5"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"
WC_POST_CSS = "true"
SHOGINN_SCRIPTS_NETLIFY = "URL"

[context.deploy-preview]
SHOGINN_SCRIPTS_NETLIFY = "DEPLOY"
HUGO_BUILDFUTURE = "true"

[context.branch-deploy]
SHOGINN_SCRIPTS_NETLIFY = "DEPLOY"

[[plugins]]
package = "netlify-plugin-hugo-cache-resources"

[plugins.inputs]
debug = true