---
name: Auto-Update ShoGinn Scripts
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    name: Auto Update ShoGinn Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: |
          cd ${GITHUB_WORKSPACE}
          curl -fsSL https://raw.githubusercontent.com/ShoGinn/wowchemy-scripts/main/install.sh | bash
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore(build): update ShoGinn Scripts"
          branch: build/shoginn-scripts
          delete-branch: true
          title: "chore(build): Auto-Update the ShoGinn Scripts"
          body: Ran Install for ShoGinn Scripts and Found Changes.
      - name: Check outputs
        run: |
          echo ":bangbang: This does not update workflows!" >> $GITHUB_STEP_SUMMARY
          echo ":bangbang: Check to make sure your workflows are how you want them!" >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          echo "Pull Request Number - ${{ steps.pr.outputs.pull-request-number }}" >> $GITHUB_STEP_SUMMARY
          echo "Pull Request URL - ${{ steps.pr.outputs.pull-request-url }}" >> $GITHUB_STEP_SUMMARY
